apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-gm
  annotations:
    sourceDBName: tf-test
    envName: srgt-host.dlpxdc.co
    vdbGroupName: K8s-VDB 
    vdbRepositoryName: Empty vFile Repository
    vdbStageMountpath: /mnt/test-gm
spec:
  storageClassName: de-fs-storage
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 5Gi
