apiVersion: v1
kind: Secret
metadata:
  name: delphix-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DCT_URL: {{ .Values.dctCreds.dctUrl }}
  DCT_KEY: {{ .Values.dctCreds.dctKey }}
