# Set this to true if we are using a microk8s distro
microk8s: true

# Images of the csi plugin and the sidecar container
image:
    csiDePlugin:
        # modify this parameter to point to the repository from where the csi container will be pulled from
        repository: docker-dev.delphix.com/delphix-kubernetes-driver/csi 
        tag: v1.0.0-stable
        pullPolicy: Always
    csiProvisioner:
        repository: registry.k8s.io/sig-storage/csi-provisioner
        tag: v3.5.0
        pullPolicy: IfNotPresent
    csiAttacher:
        repository: registry.k8s.io/sig-storage/csi-attacher
        tag: v4.3.0
        pullPolicy: IfNotPresent
    csiResizer:
        repository: registry.k8s.io/sig-storage/csi-resizer
        tag: v1.8.0
        pullPolicy: IfNotPresent
    nodeDriverRegistrar:
        repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
        tag: v2.8.0
        pullPolicy: IfNotPresent

# Credentials to fetch docker images from Delphix internal repository
# Update these fields with your unique parameters or credentials
dockerRegistry:
    imageCredentials:
        # registry to pull docker images from
        registry: docker-dev.delphix.com
        # username to login to docker registry
        username: gaurav.manhas@delphix.com 
        # password to login to docker registry
        password: cmVmdGtuOjAxOjE3Mjc1MTI0OTc6cU5Oc09Hc3JoOVpkMGpTTHZzYlg0Z0NFNW82
        # emailId for above username
        email: gaurav.manhas@delphix.com

# Update these fields with your unique parameters or credentials
dctCreds:
    # URL for the dct instance
    dctUrl: dct101.dlpxdc.co
    # dct api key for the above instance without the 'apk' part. For eg: 1.ABCDEFG
    dctKey: 1.pvR2JlMe9MEWHHV38yhNPbGMOHV9W1R2iiGYguXXSgskSIlAlyeNxiDmESFGNBLC 

# Default values for annotations.
# Update these fields with your unique parameters or credentials
default:
    scheme: https
    tlsInsecureSkipVerify: true
    Annotations:
        sourceDBName: tf-test
        envName: srgt-host.dlpxdc.co
        vdbGroupName: K8s-VDB
        vdbRepositoryName: Empty vFile Repository
        vdbStageMountpath: /mnt/vdb 
